name: CI/CD

on:
  workflow_dispatch:
  pull_request: 
    branches: main
  push:
    branches: [main]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"
  val_test:
    runs-on: ubuntu-latest
    needs: [build] 
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"
        - name: testing
          run: 
            python val_test.py
  file_is_correct_test:      
    runs-on: ubuntu-latest
    needs: [build, val_test] 
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"
        - name: testing
          run: 
            python file_is_correct_test.py
  time_test:      
    runs-on: ubuntu-latest
    needs: [build, val_test, file_is_correct_test] 
    steps:
        - name: checkout perository
          uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: "3.10"      
        - name: testing time
          run:
            python file_is_correct_test.py
